Add owners
pymanceva/pet-hotel pull request #19
Opened 2023-11-11 09:13 UTC by RodionovRL

Запутался в сквоше коммитов. Если готовы мне помочь, буду рад.

2023-11-16 19:38 UTC, alisilakg reviewed
В целом, я не нашла ошибок. У меня всё запускалось. Ручное тестирование через постман показало, что всё работает.

Замечания в основном относятся к codestyle.
а не надо  ли добавить в shema.sql удаление таблицы owners?

2023-11-16 19:38 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/owner/OwnerControllerIntegrationTest.java
> +class OwnerControllerIntegrationTest {
В этом файле есть несколько не используемых импортов и неиспользуемый UserService

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/controller/OwnerController.java
> +    private static final String USER_ID = "X-PetHotel-User-Id";
Мне нравиться, что хэдер вынесен в константу

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/controller/OwnerController.java
> +    @ResponseStatus(HttpStatus.OK)
Статус OK выдаётся по умолчанию, можно эту строчку убрать здесь и далее

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/dto/mapper/OwnerMapper.java
> +    Owner toOwner(OwnerDto ownerDto);
Этот метод нигде не используется

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/dto/NewOwnerDto.java
> +import jakarta.validation.constraints.Email;
неиспользуемый импорт

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/model/Owner.java
> +import jakarta.validation.constraints.Pattern;
неиспользуемый импорт

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/repository/OwnerRepository.java
> +//    Optional<List<User>> findAllByRoleIn(List<Roles> roles);
закомменченный код + неиспользуемые импорты

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +public class OwnerServiceImpl implements OwnerService {
есть неиспользуемые импорты

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +        log.info("ownerService: has been added owner={}", addedOwner);
это мелочь, но кажется мы договаривались об одинаковом стиле логов... 
здесь и дальше

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +        }
не слишком ли громоздкий метод? может быть стоит вынести изменение каждого поля в отдельный метод?

2023-11-16 19:38 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +        log.info("ownerService: has been delete owner with id={}", ownerId);
Не нужно ли выбрасывать NFE, если приiлетел запрос на удаление пользователя, который не существует?

2023-11-18 05:28 UTC, RodionovRL commented
Спасибо. Всё по делу. За кодстайл отдельный пардон. Постараюсь впредь не допускать непроверенного кодстайла в пулл реквесты.

2023-11-21 17:15 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/owner/controller/OwnerController.java
> +    private static final String USER_ID = "X-PetHotel-User-Id";
Спасибо =)

2023-11-21 18:01 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +        }
Я ни панимат =))
Не понял, что ты здесь предлагаешь.

2023-11-21 19:04 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/owner/service/OwnerServiceImpl.java
> +        }
Ладно. Думаю, что это не принципиально.

2023-11-21 19:07 UTC, alisilakg approved these changes

2023-11-21 19:11 UTC, alisilakg requested changes, later dismissed
Нужны изменения в связи с разработанным сценарием и диаграммой

2023-11-22 03:11 UTC, RodionovRL commented
Да. Сегодня будем обсуждать на созвоне.

2024-05-23 07:57 UTC, RodionovRL commented
[Карточка с задачей add Owners](https://nkiblyk.kaiten.ru/space/167883/card/26906268)

2024-05-27 10:05 UTC, pymanceva requested changes
Очень круто, новые фишечки прям классные - загляденье) Не смотрела тесты, только формально прогнала 2 готовых тест-класса, что все зеленое. Также у меня вторую неделю неделю не грузит draw.io, чтобы посмотреть ER-диаграмму, где прописаны все ограничения полей, возможно нужен впн теперь, не знаю, пока не дошли руки. Так что принимаю на веру, что размеры полей и тп отражены верно)
Все комментарии - больше обсудить что и как, что-то поправим, что-то оставим.

2024-05-27 10:05 UTC, pymanceva commented on specification/pet-hotel-owner-spec.yaml
> +      description: backend server для тестирования кода и работы фронтэнда
кажется описания местами перепутались - localhost как раз Local server for develop, а 212.109.192.9 для фронта

2024-05-27 10:05 UTC, pymanceva commented on specification/pet-hotel-owner-spec.yaml
> +                message: "User with role=FINANCIAL, hasn't access for browse this information"
ни на что не влияет, кроме красоты, наверное, но текст ошибки другой: User with role=FINANCIALs, can't access for this action

2024-05-27 10:05 UTC, pymanceva commented on specification/pet-hotel-owner-spec.yaml
> +                message: "User with role=FINANCIAL, hasn't access for browse this information"
так же текст ошибки

2024-05-27 10:05 UTC, pymanceva commented on specification/pet-hotel-users-spec.yaml
> +  - url: https://212.109.192.9:443
у клиентов и юзеров в спецификациях почему-то разные адреса удаленного сервера. Так и задумано?

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/controller/Direction.java
> +public enum Direction {
мне было очень сложно по названию понять, что это за зверь - пришлось пройти через весь контроллер, чтобы найти где используется это Direction, и все равно было не до конца понятно. Пришлось читать в свагере русскую версию. Может переименуем в направление поиска, т.е. SearchDirection? Или параметр поиска, SearchParam, например

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +            @RequestBody SearchOwnerDto searchOwnerDto,
Почему такой выбор построения поиска? Мне видится более простым вариант, где номер телефона или имя передается вторым параметром. При таком раскладе это будет GET-запрос, что логично, так как мы именно получаем инфо, а не постим ее. Также не придется создавать дополнительный класс SearchOwnerDto

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/dto/NewOwnerDto.java
> +//    @NotBlank(message = "Field: lastName. Error: must not be blank.")
забытый коммент

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/model/Owner.java
> +    @Column(name = "optional_phone_owners", nullable = false)
optionalPhone же допустимо null, т.е. nullab;e=true

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/model/Owner.java
> +public class Owner {
должны ли оунеры как-то знать своих питомцев? Или питомец знает своего оунера и хватит?

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/service/OwnerServiceImpl.java
> +    public void deleteOwnerById(Long requesterId, Long ownerId) {
не будем продолжать традицию с одним походом в базу при удалении? В остальных сущностях удаление так делали, в тех же юзерах.

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/utility/UpdateField.java
> +public final class UpdateField {
крутая штука, очень удобно! Надо не забыть у остальных красоту навести с использованием этого класса потом

2024-05-27 10:05 UTC, pymanceva commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
не совсем ясна суть данной проверки. Параметры метода, помеченные с помощью @RequestParam, обязательны по умолчанию (статья https://www.baeldung.com/spring-request-param, раздел 4). Таким образом, null параметр вызовет MissingServletRequestParameterException и до поля проверки не дойдет. Или же ты проверяешь результат результат преобразования строки в Direction? В таком случае может перенести эту проверку в класс Direction?

2024-05-27 10:10 UTC, RodionovRL commented on specification/pet-hotel-owner-spec.yaml
> +      description: backend server для тестирования кода и работы фронтэнда
Да, здесь я немного напутал. Веселился как мог =) Исправлю сейчас же =)

2024-05-27 10:11 UTC, RodionovRL commented on specification/pet-hotel-owner-spec.yaml
> +                message: "User with role=FINANCIAL, hasn't access for browse this information"
И здесь исправлю. Пусть будет красота =)

2024-05-27 10:11 UTC, RodionovRL commented on specification/pet-hotel-owner-spec.yaml
> +                message: "User with role=FINANCIAL, hasn't access for browse this information"
аналогично

2024-05-27 10:12 UTC, RodionovRL commented on specification/pet-hotel-users-spec.yaml
> +  - url: https://212.109.192.9:443
Ну у нас через 443 порт работает теперь и через https. Хотя и по старому тоже работает =)))

2024-05-27 10:13 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/Direction.java
> +public enum Direction {
Ну логика моя начиналась с пути эндпоинта, а там как раз /search =)

2024-05-27 10:13 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/model/Owner.java
> +    @Column(name = "optional_phone_owners", nullable = false)
Верно =)

2024-05-27 10:19 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/model/Owner.java
> +public class Owner {
Я подумал, что связку Owner-Питомец - будем реализовывать отдельной задачей, поэтому не предусматривал их связи.

2024-05-27 10:21 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/service/OwnerServiceImpl.java
> +    public void deleteOwnerById(Long requesterId, Long ownerId) {
Да, запамятовал. Переделаю.

2024-05-27 10:30 UTC, RodionovRL commented on src/main/java/ru/modgy/utility/UpdateField.java
> +public final class UpdateField {
Ага. Меня давно это место мучило своей корявостью и тут я придумал, как быть =)
Рад, что тебе понравилось =)

2024-05-27 10:34 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
Да, это проверка, на случай, если неправильно преобразовался Direction. Перенести как? Что-то не соображу.

2024-05-27 10:35 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
Мы же не можем при всех случаях неправильного преобразования Direction выбрасывать BadRequestException

2024-05-29 15:19 UTC, pymanceva commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
Ну можно иную ошибку с тем же кодом бросить, кастомную например

2024-06-03 12:13 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
А какой статус при этом оправлять?

2024-06-03 12:23 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +        if (direction == null) {
В общем, не думаю, что есть какой-то смысл в том, чтобы убрать эту обработку внутрь Direction

2024-06-03 14:20 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/Direction.java
> +public enum Direction {
Переименовал

2024-06-04 07:45 UTC, pymanceva approved these changes

2024-06-06 07:58 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/controller/OwnerController.java
> +            @RequestBody SearchOwnerDto searchOwnerDto,
Чтобы не передавать в открытую (в адресной строке) чувствительных данных. Было у нас обсуждение этого в тележке.
Get запрос не позволяет отправлять в себе body.

2024-06-06 09:21 UTC, RodionovRL commented
**0.0.12: Реализована работа с клиентами(хозяевами постояльцев) отеля:**
- создание
- получение списка всех клиентов
- получение по id
- редактирование данных клиента
- получение краткой информации о последних нескольких зарегистрированных клиентах
- получение краткой информации о клиенте по его id
- Проверка наличия в базе клиента с указанным номером телефона
- Поиск клиента по ФИО или номеру основного и дополнительного телефонов

Карточка: *<https://nkiblyk.kaiten.ru/26906268>*  
Api: *<https://github.com/pymanceva/pet-hotel/blob/efed8fb9bbd026f8cab858a21672a84bdb4e151f/specification/pet-hotel-owner-spec.yaml>*

2024-06-06 09:21 UTC, merged