Add comments for pets
pymanceva/pet-hotel pull request #20
Opened 2023-11-17 21:40 UTC by alisilakg

2023-11-18 22:13 UTC, pymanceva requested changes

2023-11-18 22:13 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/controller/CommentController.java
> +        log.info("Получен POST-запрос к эндпоинту: '/users/{userId}/comments' на добавление комментария " +
мы обсуждали ранее единый стиль по логированию, есть в телеге в теме "правила", там короче

2023-11-18 22:13 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/mapper/CommentMapper.java
> +//    public Comment toComment(NewCommentDto newCommentDto, User user, Event event) {
комменты со шпаргалкой из старого проекта подчистить)))

2023-11-18 22:13 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/service/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
стоит добавить логирование, как минимум для методов, которые вносят изменения в БД (добавление, обновление и удаление комментов), а лучше во всем классе

2023-11-18 22:13 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/service/CommentServiceImpl.java
> +        } else {
думаю, стоит предусмотреть такую возможность и у админа с боссом, мало ли что там няня настрочит - а потом никто удалить не может)

2023-11-18 23:33 UTC, pymanceva reviewed
Стоит добавить методы и эндпоинт для получения комментариев о конкретном питомце, а не только по конкретному юзеру.

2023-11-18 23:33 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/controller/CommentController.java
> +@RequestMapping(path = "/comments")
Если комментарий относится к конкретному питомцу - не должно ли это отражаться в пути, типа localhost/pet/{id}/comments? Это вопрос на обсуждение, не требование.

2023-11-20 11:12 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/comment/controller/CommentController.java
> +@RequestMapping(path = "/comments")
В методах, где требуется id питомца, я так и делаю, правда в другом порядке

@PostMapping("/comments/pets/{petId}")
    @GetMapping("/comments/pets/{petId}")

2023-11-20 11:12 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/comment/controller/CommentController.java
> +        log.info("Получен POST-запрос к эндпоинту: '/users/{userId}/comments' на добавление комментария " +
исправила

2023-11-20 11:13 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/comment/mapper/CommentMapper.java
> +//    public Comment toComment(NewCommentDto newCommentDto, User user, Event event) {
убрала

2023-11-20 11:13 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/comment/service/CommentServiceImpl.java
> +public class CommentServiceImpl implements CommentService {
добавила

2023-11-20 11:14 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/comment/service/CommentServiceImpl.java
> +        } else {
добавила для босса, т.к. у Наташи в описании задачи обозначен именно босс. Всё таки для админа тоже добавить или нет?

2023-11-20 11:17 UTC, alisilakg commented
> Стоит добавить методы и эндпоинт для получения комментариев о конкретном питомце, а не только по конкретному юзеру.

У меня метод получения конкретного комментария по commentId и метод получения всех комментариев конкретного питомца. Получения комментариев по юзерам вообще нет. Пока не стала добавлять эти эндпоинты

2023-11-20 22:10 UTC, pymanceva approved these changes

2023-11-20 22:10 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/comment/service/CommentServiceImpl.java
> +        log.info("CommentService: crateComment, requesterId={}, commentId={}", requesterId, savedComment.getId());
опечатка в crEate

2023-11-20 22:10 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/mapper/PetMapper.java
> +    @ToPet
можешь объяснить про использование этой аннотации? Может статьи скинуть. Я так понимаю, она должна как-то помочь определять, какой именно вариант дто возвращать - обычный или для админа, он не разберусь, как это происходит. Спасибо

2023-11-21 18:08 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/mapper/PetMapper.java
> +    @ToPet
Во-первых, хочу сказать, что я не уверена в верности использования этого способа, потому что русскоязычных источников я не нашла, а английским владею не так хорошо, как хотелось бы. Поэтому не исключено, что это у меня костыль.
Во-вторых, могу рассказать, как я поняла, что можно использовать такой метод.
Изначально маппер был таким.
```java
@Mapper(componentModel = "spring", uses = {PetMapper.class, UserMapper.class})
public interface CommentMapper {
    @Mapping(source = "comment.author", target = "author")
    @Mapping(source = "comment.pet", target = "pet")
    CommentDto toCommentDto(Comment comment);
``` 
При попытке запустить код, вылетало такое сообщение: Ambiguous mapping methods found for mapping property "Pet pet" to PetDto: PetDto PetMapper.toPetDto(Pet pet), PetForAdminDto PetMapper.toPetForAdminDto(Pet pet). See https://mapstruct.org/faq/#ambiguous for more info.
Тут же есть ссылка https://mapstruct.org/faq/#ambiguous
И там я прочитала про использование аннотации

2024-03-27 18:07 UTC, closed without merging