feat: добавить спецификацию для бронирований v.1
pymanceva/pet-hotel pull request #27
Opened 2023-12-07 22:11 UTC by pymanceva

2023-12-08 18:39 UTC, alisilakg approved these changes
Я посмотрела. Мне всё понравилось. Недочётов не нашла

2023-12-09 13:06 UTC, RodionovRL requested changes
Ну и для красоты - параметр id бронирования можно тоже вынести в компоненты к хэдеру и схемам.

2023-12-09 13:06 UTC, RodionovRL commented on Specification/pet-hotel-bookings-spec.yaml
> +    BookingDto:
не нашёл поле с количеством дней, в ER оно имеется.
![image](https://github.com/pymanceva/pet-hotel/assets/114774699/fb2eea51-a7ac-4e46-b69d-cefde9c0fcb7)

2023-12-09 22:46 UTC, RodionovRL approved these changes
Прекрасно :)

2023-12-09 22:47 UTC, merged