Add categories
pymanceva/pet-hotel pull request #30
Opened 2023-12-17 23:42 UTC by pymanceva

2023-12-18 19:31 UTC, alisilakg reviewed
Посмотрела. Ты молодец! Сделала сущность категории очень быстро и качественно. 
Есть несколько небольших замечаний по валидации.
И вопрос общего характера: связь между номерами и категориями будем реализовывать как отдельную задачу?)))

2023-12-18 19:31 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +    public void deleteCategoryById(Long userId, Long catId) {
в требованиях к категориям написано: "Удаление категории возможна при отсутствии номеров с данной категорией. При наличии номеров с данной категорией удаление категории невозможно."

я не увидела этой проверки))))

2023-12-18 19:31 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/room/category/model/Category.java
> +    @Column(name = "id_category")
названия полей в БД уже обсудили, нужно множественное число))))

2023-12-18 19:31 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +        if (Objects.isNull(newCategory.getName())) {
сейчас твой код допускает следующую ситуацию: при изменении категории в поле name передаётся "" или " " и такое изменение сохраняется, хотя на поле название категории стоит ограничение минимум 1 символ и NotNull
![Снимок экрана от 2023-12-18 23-55-30](https://github.com/pymanceva/pet-hotel/assets/118027659/6be475d7-0fc1-4f07-ab02-5cfcbbb17337)

2023-12-18 19:31 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/room/category/CategoryController.java
> +                                          @RequestBody UpdateCategoryDto updateCategoryDto,
сейчас у тебя нет валидации приходящего в контроллер в качестве тела запроса UpdateCategoryDto.
Проверка на количество символов только в самой БД.
но в классе UpdateCategoryDto есть @Size

2023-12-18 22:53 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +    public void deleteCategoryById(Long userId, Long catId) {
внесла ограничение в БД

2023-12-22 00:17 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +        if (Objects.isNull(newCategory.getName())) {
Твои предложения? not null соблюдается как минимум на уровне БД. Ограничения по размеру также указаны, минимум и максимум. Да, юзер может вкатить пробелы и/или символы переноса строк и это пройдет, так как символы на месте. Как предлагаешь изменить? Если поставлю @NotBlankl  - получится, что каждый раз придется заполнять название, даже если и не хотим его менять.

2023-12-23 11:50 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +        if (Objects.isNull(newCategory.getName())) {
Можно использовать Паттерн с регулярным выражением. Разрешить только буквы и цифры, запретить без букв и цифр, не разрешать первым писать пробел и т.д.
@Pattern(regexp =

2023-12-23 12:50 UTC, RodionovRL requested changes
Молодец. Хороший код. Мне нравится. Пара комментов только.

2023-12-23 12:50 UTC, RodionovRL commented on src/main/resources/schema.sql
> +    id_category          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
id_categories
и остальные поля тоже

2023-12-23 14:20 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +        if (Objects.isNull(newCategory.getName())) {
посмотри как у меня сделан метод изменения питомца. Там проверка не только на нуль, но и на blank

2023-12-24 09:13 UTC, RodionovRL approved these changes
Аппрув. Перед мержем нужно убрать закомментированный код.

2023-12-24 09:13 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/category/service/CategoryServiceImpl.java
> +    //@Named("idToCategory")
Комменты долой

2023-12-24 09:13 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/dto/mapper/RoomMapper.java
> +    //@Mapping(source = "newRoomDto.categoryId", target = "category", qualifiedByName = "idToCategory")
Комменты долой

2023-12-25 06:41 UTC, alisilakg approved these changes
я не нашла ошибок и недочётов. Всё работает

2023-12-25 07:35 UTC, merged