добавила все необходимые поля в карточку питомца
pymanceva/pet-hotel pull request #31
Opened 2023-12-18 12:12 UTC by alisilakg

2023-12-18 22:37 UTC, pymanceva requested changes
Огромный блок, круто! Пара комментов, в основном опечатки, поработала здорово! Единственное - не вижу в твоей ветке папки с версиями, в девелопе они есть. Либо не все стянула себе перед PR, либо может они у тебя в гитигнор попали? Надо поправить, чтобы их из девелопа не затереть случайно)

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/NewPetDto.java
> +    @Length(max = 30, message = "validation sex size error")
если это валидация пола - то надо над полем sex разместить. Если же это для поля цвет - тогда текст ошибки подправить.

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/NewPetDto.java
> +    @PastOrPresent(message = "Field: birthDate. Error: must be past or present.")
по ТЗ и ERD строго прошедшее время, не настоящее

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/UpdatePetDto.java
> +    @PastOrPresent(message = "Field: birthDate. Error: must be past or present.")
снова дата рождения present

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/UpdatePetDto.java
> +    @Length(max = 30, message = "validation sex size error")
текст ошибки

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/UpdatePetDto.java
> +    @Future(message = "Field: vetVisitDate. Error: must be future.")
а тут наоборот, вроде present не хватает, в NewPetDto указана аннотация FutureOrPresent, ну и по логике - можно поставить сегодняшнее число, если собака заезжает с течкой

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/service/PetServiceImpl.java
> +    public PetDto getPetById(Long requesterId, Long petId) {
а как будет осуществляться сокрытие данных о владельце от пользователя с ролью user? и финансист имеет вообще доступ к карточкам питомцев? Мне кажется не должен, для статистики отчетов ему это не нужно

2023-12-18 22:37 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/pet/service/PetServiceImpl.java
>      public void deletePetById(Long requesterId, Long petId) {
в этом методе получается не проверяется, произошло ли удаление, так? Проверяем наличие питомца изначально, затем отправляем запрос на удаление, но не отслеживаем, сработало ли в каждом конкретном случае. Предлагаю проверять этот нюанс, мало ли. У меня проверка через integer, который возвращается из репо по методу удаления (дает число удаленных полей, у нас должно быть 1), только надо в интерфейсе репо метод добавить. Можешь  у меня глянуть, если так не делала. Это, кстати, оптимизирует обращения к БД в рамках метода - заранее не проверяем наличие питомца в БД, сразу удаление и по результату понимаем, что и как

2023-12-20 06:59 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/service/PetServiceImpl.java
> +    public PetDto getPetById(Long requesterId, Long petId) {
>
![Снимок экрана от 2023-12-20 11-57-52](https://github.com/pymanceva/pet-hotel/assets/118027659/ab81bd10-e6b5-4a42-929d-25f64ff77b79)

ответ от фронтов

![Снимок экрана от 2023-12-20 11-58-54](https://github.com/pymanceva/pet-hotel/assets/118027659/c77a7a84-85e4-491e-89e0-f9199f02f551)

2023-12-20 07:01 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/service/PetServiceImpl.java
> +    public PetDto getPetById(Long requesterId, Long petId) {
поэтому будет краткое дто клиента с фио и рейтингом, который для нянь фронт не покажет.
пока решили на фронте управлять всей видимостью/невидимостью полей. Как вариант, можно разные дто сделать. Я не знаю, как лучше. Фронт говорит, что им без разницы

2023-12-20 07:01 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/service/PetServiceImpl.java
> +    public PetDto getPetById(Long requesterId, Long petId) {
про финансиста в сценарии ничего нет, поэтому в коде его тоже нет

2023-12-20 07:53 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/UpdatePetDto.java
> +    @Future(message = "Field: vetVisitDate. Error: must be future.")
убрала любые ограничения. Если Наташа возразит - верну

2023-12-21 07:54 UTC, pymanceva approved these changes
Всё огонь! Мне всё нравится

2023-12-24 11:53 UTC, RodionovRL approved these changes
Всё хорошо. Честно скажу, код я не запускал. Ревью делал глазами.
Вопросы только по многочисленным комментам, то там, то здесь встречающимся.

2023-12-24 11:53 UTC, RodionovRL commented on pet-hotel-versions/pet-hotel-back-0.0.3/Dockerfile
> +COPY ./target/*.jar app.jar
Здесь не нужна папка target, jar-файл лежит не в ней.

2023-12-24 11:53 UTC, RodionovRL commented on pom.xml
> +	<version>0.0.6-SNAPSHOT</version>
Если обозначена версия 6, то нужно для нёё соответсвующую инфраструктуру (папку, лог изменений и т.д.)

2023-12-24 11:53 UTC, RodionovRL commented on pom.xml
> +	<version>0.0.6-SNAPSHOT</version>
Ну и с вопросом номера версии - почему 6?

2023-12-24 11:53 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/NewPetDto.java
> +//    private long ownerId;
Комменты-комменты

2023-12-24 11:53 UTC, RodionovRL commented on src/main/resources/application.properties
> +
кстати говоря, swagger-то, наверное теперь здесь и не нужен. Мы же не из кода его теперь генерим&

2023-12-25 06:57 UTC, alisilakg commented on pom.xml
> +	<version>0.0.6-SNAPSHOT</version>
![Снимок экрана от 2023-12-25 11-45-12](https://github.com/pymanceva/pet-hotel/assets/118027659/8785ef3a-ce4b-498a-b68c-c247fca77628)
начала работу над веткой. поменяла версию на следующую по порядку за версией Олеси по категориям.
получу аппрув - сделаю инфраструктура, что соответствует правилам, обозначенным в закреплённом сообщении в беседе back_server

2023-12-25 06:58 UTC, alisilakg commented on pet-hotel-versions/pet-hotel-back-0.0.3/Dockerfile
> +COPY ./target/*.jar app.jar
поменяю, когда после аппрува буду вносить изменения в папку с версиями

2023-12-25 06:59 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/pet/dto/NewPetDto.java
> +//    private long ownerId;
я разкомменчу, когда будут оунеры готовы

2023-12-25 07:03 UTC, alisilakg commented on src/main/resources/application.properties
> +
тоже могу удалить, когда буду версии менять

2023-12-25 07:09 UTC, RodionovRL commented on pom.xml
> +	<version>0.0.6-SNAPSHOT</version>
Рановато с версией - её после аппрува надо назначать, перед созданием jar файла непосредственно.

2023-12-26 05:33 UTC, merged