Fix users last middle first names
pymanceva/pet-hotel pull request #32
Opened 2023-12-20 19:22 UTC by RodionovRL

2023-12-21 12:57 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserService.java
>      UserDto getUserById(Long requesterId, Long id);
лучше избегать переменных с названием просто id, непонятно чье айди имеется ввиду

2023-12-21 12:57 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserService.java
>      void deleteUserById(Long id, Long aLong);
второй параметр - не ясно, что за зверь

2023-12-21 12:57 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +    public List<UserDto> getAllUsers(Long requesterId) {
я верно понимаю, у нас только управляющий имеет доступ к юзерам? Ну судя по ТЗ, там админ ничего делать не может, вы обсуждали это с Наташей?

2023-12-21 12:57 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +        User user = findUserById(userId);
в такой реализации не проверяем, а произошло ли в итоге удаление из базы, плюс лишнее обращение в БД происходит. Предлагаю дописать в репозиторий метод удаления по айди, возвращающий integer, равный числу удаленных строк и проверять этот интежер. Если 0 - ничего не удалилось,т.е. такой объект не найден, если 1 - значит удаление прошло успешно

2023-12-21 12:57 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +    //TODO
видимо уже выполнено - можно удалять коммент

2023-12-21 21:50 UTC, alisilakg reviewed
Ты молодец, при не хватке времени умудряешься написать хороший код))))
Я начала проверять, но в классах User и дтошках путаница с аннотациями, и поэтому потестить пользователей через постман не получится нормально.Поправь, пожалуйста, и можно будет дальше ревьюить)))

2023-12-21 21:50 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/user/dto/NewUserDto.java
> +    @NotBlank(message = "Field: lastName. Error: must not be blank.")
Руслан, надо в этом классе аннотации поправить в соответствии со сваггером

2023-12-21 21:50 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/user/dto/UpdateUserDto.java
> +    @NotNull(message = "Field: role. Error: must not be null.")
Роль пользователя не может быть нуллевой при изменении пользователя?

2023-12-21 21:50 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/user/model/User.java
> +    @Column(name = "last_name_users", nullable = false)
здесь nullable нужно поправить. Убрать или оставить в соответствии со сваггером. Из-за них бд не записывает пользователей с полями null, хотя в схеме not null нет

2023-12-23 09:44 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +    public List<UserDto> getAllUsers(Long requesterId) {
Обсудили. Делаем в соответствии со спецификацией. Наташа ТЗ подправит.

2023-12-23 09:47 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +        User user = findUserById(userId);
По поводу проверки - сделаю, давно хотел у тебя перенять этот опыт.
По поводу лишнего обращения - для проверки прав на удаление определённого пользователя нужно достать его из базы.

2023-12-23 10:01 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +        User user = findUserById(userId);
ну а после того, как достал его из базы, глупо как-то проверять результат удаления =)

2023-12-23 10:04 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/user/service/UserServiceImpl.java
> +        User user = findUserById(userId);
но я всё-же сделаю. Пусть будет однообразненько =)

2023-12-25 22:56 UTC, pymanceva requested changes
В остальном все здорово, только паттерн добавить

2023-12-25 22:56 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/dto/NewUserDto.java
> +    @Size(min = 2, max = 30, message = "validation name size error")
здесь и далее - давай тогда добавим паттерн, как Наташа писала: минимум 2 буквы. Предлагаю поставить на все 3 имени, то есть middle и last могут быть null, но если они не null - то как минимум 2 буквы содержат

2023-12-25 22:56 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/user/dto/UpdateUserDto.java
> +    private String lastName;
и здесь также, мин 2 буквы

2023-12-26 04:16 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/user/dto/NewUserDto.java
> +    @Size(min = 2, max = 30, message = "validation name size error")
Присоединяюсь к Олесе. Сейчас можно создать пользователя, у которого имя будет состоять из 3х пробелов

2023-12-26 04:18 UTC, alisilakg reviewed
всё работает отлично

2023-12-26 04:18 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/user/dto/UpdateUserDto.java
>      private Long id;
здесь не понятно зачем нужен id

2023-12-27 05:16 UTC, alisilakg reviewed
Код не запускается, потому что когда стягивал к себе изменения схему таблицы с питомцами стянул как-то неправильно))))

2023-12-27 05:16 UTC, alisilakg commented on src/main/resources/schema.sql
>      id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Руслан, вот этого здесь не должно быть)))

2024-01-05 09:33 UTC, pymanceva approved these changes

2024-01-09 09:28 UTC, alisilakg approved these changes

2024-01-10 09:24 UTC, alisilakg approved these changes
Потыкала в постмане. Всё работает)))

2024-01-10 09:24 UTC, alisilakg commented on pet-hotel-versions/pet-hotel-back-0.0.7/CHANGELOG.md
> +- изменение состояния учётной записи
Вот только в этой строчке мне было не очевидно, что значит изменить состояние учётной записи(это ведь изменить поле isActive, я правильно поняла?), выше про это же поле сказано "статус"....

2024-01-10 09:27 UTC, RodionovRL commented on pet-hotel-versions/pet-hotel-back-0.0.7/CHANGELOG.md
> +- изменение состояния учётной записи
Да, это про isActive. Подправлю перед мержем.

2024-01-10 13:44 UTC, merged