Add bookings
pymanceva/pet-hotel pull request #35
Opened 2024-01-13 11:51 UTC by pymanceva

2024-01-19 18:25 UTC, RodionovRL requested changes
Молодец :) Проделана большая и хорошая работа, и всё же есть вопросы и замечания, которые требуют вмешательства.

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +    final private UserRepository userRepository;
Замечание ко всему коду:

Порядок использования модификаторов:

public / private / protected
abstract
static
final
transient
volatile
**default**
synchronized
native
strictfp

2024-01-19 18:25 UTC, RodionovRL commented on src/main/resources/schema.sql
> +    CONSTRAINT check_out_later_than_in CHECK (check_out_date_bookings >= check_in_date_bookings)
Подобные проверки в базе, конечно, имеют место быть для дополнительного контроля. Но база - это скорее полка, нежели часть кода приложения. В базе нужно хранить информацию, а проверять правильность полученных данных нужно в логике.
Касается всего кода.

2024-01-19 18:25 UTC, RodionovRL commented on Specification/pet-hotel-bookings-spec.yaml
>            description: Причина закрытия номера. Обязательно для бронирования типа TYPE_CLOSING
Не проверяется при создании бронирования "type": "TYPE_CLOSING".
Можно создать бронирование с "type": "TYPE_CLOSING" и "reasonOfStop": null

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +        newBooking.setPets(pets);
Похоже на N+1.

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/dto/NewBookingDto.java
> +    private Double price;
@Min и @Max можно заменить на @Size, но это дело вкуса.

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/dto/UpdateBookingDto.java
> +    @Size(max = 150)
О, а здесь @size

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/dto/mapper/BookingMapper.java
> +    }
Молодец. Мне нравится =)

2024-01-19 18:25 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +                    .map(this::findPetById)
N+1
ну и далее

2024-01-19 18:25 UTC, RodionovRL commented on src/main/resources/application.properties
> +
А зачем в пропертях Сваггер?

2024-01-19 18:25 UTC, RodionovRL commented on src/main/resources/schema.sql
> +    CONSTRAINT check_out_later_than_in CHECK (check_out_date_bookings >= check_in_date_bookings)
Надо в сервисе проверять.

2024-01-19 19:06 UTC, alisilakg reviewed
Проделана огромная работа! Ты молодец)))

2024-01-19 19:43 UTC, alisilakg reviewed
Огромная работа проделана!!!! Ты молодец. Единственный вопрос про вот эти все ограничения на изменение статусов....

2024-01-19 19:43 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +    public BookingDto updateBooking(Long userId, Long bookingId, UpdateBookingDto updateBookingDto) {
Олеся, а ты не работала над ограничениями смены статусов для типа бронирования ?
![Снимок экрана от 2024-01-20 00-32-47](https://github.com/pymanceva/pet-hotel/assets/118027659/7e0d64d7-46a5-4b83-b97b-c40269f4ff0e)

2024-01-19 19:43 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +    public BookingDto updateBooking(Long userId, Long bookingId, UpdateBookingDto updateBookingDto) {
Или всеми этими ограничениями будет заниматься фронт?

2024-01-19 21:56 UTC, pymanceva commented on src/main/resources/schema.sql
> +    CONSTRAINT check_out_later_than_in CHECK (check_out_date_bookings >= check_in_date_bookings)
не совсем согласна с этим моментом. Зачем пускать невалидные данные в сервис? Это проверяется на уровне валидации входного ДТО, то есть невалидные данные не будут даже обрабатываться сервисом и тратить ресурсы программы. На уровне БД доп ограничения "на всякий", чтобы и инсертом в схеме кривые данные не влетели

2024-01-19 21:59 UTC, pymanceva commented on Specification/pet-hotel-bookings-spec.yaml
>            description: Причина закрытия номера. Обязательно для бронирования типа TYPE_CLOSING
мы же обсуждали, что это на уровне фронта делается и они нам передают нужные данные. Если я не так поняла суть - нам нужен доп созвон на обсуждения еще огромной массы деталей того, как работать с подобными ситуациями, когда одной сущностью обрабатываются разные типы бронирований или разные виды питомцев, например

2024-01-19 22:06 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +    public BookingDto updateBooking(Long userId, Long bookingId, UpdateBookingDto updateBookingDto) {
Это обсуждалось на созвоне, что над этим еще надо поработать и там у меня еще доп вопросы к Наташе, которые я хотела обсудить. Потому что с последними двумя ограничениями я не могу понять логику. Короче, пока толком не трогала.

2024-01-19 22:07 UTC, pymanceva commented on src/main/resources/application.properties
> +
пользуюсь автогенерацией доки при обновлении свагера после написания кода фактического, мне так быстрее и удобнее, из готового нужные блоки копипастить и сверять

2024-01-19 22:10 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +        newBooking.setPets(pets);
Что ты имеешь ввиду? Линейную алгоритмическую сложность или что? У меня и в учебных проектах было также. Мне мой ревьюер тогда не дал ответа, как это реализовать без обращения к БД число раз, равное размеру списка. Если есть варианты - в студию)

2024-01-19 23:00 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/dto/NewBookingDto.java
> +    private Double price;
А как насчет подобного? https://stackoverflow.com/questions/11189398/difference-between-sizemax-value-and-minvalue-and-maxvalue

Я понимаю так, что @Size с числовыми данными не используется, так как ограничивает число символов, а не значение числа. При попытке поставить @Size на полях типа Double выдает такую ошибку: 
ERROR 18864 --- [nio-8080-exec-6] r.d.P.exception.handler.ErrorHandler     : EH: Internal Server Error. HV000030: No validator could be found for constraint 'jakarta.validation.constraints.Size' validating type 'java.lang.Double'. Check configuration for 'price'

2024-01-20 02:30 UTC, RodionovRL commented on src/main/resources/schema.sql
> +    CONSTRAINT check_out_later_than_in CHECK (check_out_date_bookings >= check_in_date_bookings)
В данном случае я о дате заезда и дате выезда. Проверка того, что дата заезда не позже даты выезда проверяется только базой.

2024-01-20 02:34 UTC, RodionovRL commented on Specification/pet-hotel-bookings-spec.yaml
>            description: Причина закрытия номера. Обязательно для бронирования типа TYPE_CLOSING
Я рассуждал с позиции того, что фронт - это просто отображение. Если в данном случае принято такое решение, то ОК. Из описания API я не правильно понял, видимо.

2024-01-20 02:39 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +        newBooking.setPets(pets);
Я имею в виду ошибку N+1. 
"Проблема N+1 запросов возникает, когда получение данных из БД выполняется за N дополнительных SQL-запросов для извлечения тех же данных, которые могли быть получены при выполнении основного SQL-запроса."

Это сильно перегружает базу. Твой ревьювер с Практикума - бестолочь, если не пояснил тебе такое.

Это нужно делать за один запрос, выбрать все необходимые данные. Иначе базу мы подвесим очень быстро :)

2024-01-20 02:40 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/booking/dto/NewBookingDto.java
> +    private Double price;
А вот здесь я и не знал. Видимо @size только для длинны строк.
Век живи - век учись. Продолжение вы знаете :)

2024-01-20 02:42 UTC, RodionovRL commented on src/main/resources/application.properties
> +
Понятно. В таком случае можно ещё аннотациями сваггера пользоваться, для дополнительного опыта :)

2024-01-23 22:28 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImpl.java
> +        newBooking.setPets(pets);
переписываю на использование дто вместо id питомцев и столкнулась с дилеммой. Нам принять на веру, что все переданные PetDto верные и соответствующие питомцы с такими id действительно имеются в БД, потому как по идее они изначально с бэка из БД приходят на фронт, там их выбирают в поля нового бронироавния и снова возвращают назад на бэк. Если да - то наверное я потом перепишу бронирования и roomId тоже заменю на roomDto

2024-01-29 05:49 UTC, alisilakg commented on src/main/resources/schema.sql
> +    status_bookings            VARCHAR(50)                             NOT NULL,
Это поле в диаграмме в кайтане ограничение 150, у тебя 50. Я правильно понимаю, что с Наташей вы договорились, просто в диаграмме не исправлено?

2024-01-29 05:49 UTC, alisilakg commented on src/main/resources/schema.sql
> +    type_bookings              VARCHAR(50)                             NOT NULL,
Здесь тоже

2024-01-29 05:49 UTC, alisilakg commented on src/main/resources/schema.sql
> +    reason_of_stop_bookings    VARCHAR(50)                                     ,
и здесь

2024-01-29 05:49 UTC, alisilakg commented on src/main/resources/schema.sql
> +    comment_bookings           VARCHAR(150)                                    ,
Здесь "comment", в диаграмме в кайтане "text". На мой взгляд, может начаться путаница...

2024-01-29 05:49 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/booking/model/Booking.java
> +    private Double amount;
В кайтане "Сумма бронирования считается автоматически при заполненном поле Стоимость бронирования как Стоимость бронирования*Количество дней. "
Я правильно поняла, что ты это не реализовала? 

![Снимок экрана от 2024-01-29 10-06-44](https://github.com/pymanceva/pet-hotel/assets/118027659/b5a3f18f-dcd1-41e4-a768-fc95ff9d581a)

2024-01-29 05:49 UTC, alisilakg commented on src/main/java/ru/dogudacha/PetHotel/booking/model/Booking.java
> +    private Double price;
В кайтане: "Сумма бронирования не может быть < Цена бронирования "
Ты это не реализовывала?
![Снимок экрана от 2024-01-29 10-10-37](https://github.com/pymanceva/pet-hotel/assets/118027659/e857ec87-746f-4ce8-88a9-08983e44e38b)

2024-01-29 05:49 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/booking/service/BookingServiceImplTest.java
> +        UpdateBookingDto updateBookingDto = UpdateBookingDto.builder()
В этом и в следующем тестах есть повторяющийся код с созданием объектов. Я бы вынесла наверх, в поля класса...

2024-01-30 22:25 UTC, pymanceva commented on src/main/resources/schema.sql
> +    comment_bookings           VARCHAR(150)                                    ,
это точно с Наташей обсуждали, чтобы постаавить comment. Так как свойство text может быть присуще разным сущностям. Вдруг потом и комменты, и причины отмен и т.п. вынесем в сущности отдельные и у всех будет текст.

2024-01-30 22:29 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/model/Booking.java
> +    private Double amount;
нет, это же часть для фронта. Там логика такая: юзеру предварительно высвечивается сумма бронирования, рассчитанная как цена*кол-во дней, однако ее можно изменить вручную, добавить стоимость доп услуг или наоборот сделать скидку, все посчитать отдельно и тут уже итого отразить. Соответственно, на фронте клиенту это посчитают и напишут, но на бэк придет не обязательно расчетная сумма, поэтому просто конкретное число принимается либо по дефолту 0.

2024-01-30 23:44 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/booking/model/Booking.java
> +    private Double price;
спасибо, забыла обсудить это с Наташей, пока не правлю - Наташе вопрос задала, если что - с другой задачкой допишу проверку.

2024-01-31 04:31 UTC, alisilakg approved these changes

2024-02-02 09:58 UTC, RodionovRL approved these changes
Approve :)

2024-02-05 14:11 UTC, merged