test: покрыть тестами users
pymanceva/pet-hotel pull request #36
Opened 2024-01-18 14:42 UTC by RodionovRL

2024-01-19 22:44 UTC, pymanceva requested changes
Все посмотрела, но у меня интеграционные сервиса падают. И очень хочу послушать, для чего новый класс. Выглядит круто, вопрос нужен ли он в дополнение или если его чуть расширить, то он заменяет интеграционные тесты сервиса?

2024-01-19 22:44 UTC, pymanceva commented on src/test/java/ru/dogudacha/PetHotel/user/IntegrationTest.java
> +public class IntegrationTest {
добавь, пожалуйста, в названии класса слово User, чтобы по названия файла без пути тоже было ясно, что тут тестим. Ну а в целом - было бы неплохо рассказать, почему решил такое тестирование добавить. Есть отдельно интегр тесты контроллера и сервиса, зднсь же еще и общие. Проверить взаимодействие контроллера с сервисом?

2024-01-19 22:44 UTC, pymanceva commented on src/test/java/ru/dogudacha/PetHotel/user/IntegrationTest.java
> +    final String userLastName = "Мартынов";
это пасхалочка?)))))

2024-01-19 22:44 UTC, pymanceva commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceIntegrationTest.java
> +    final String userFirstName = "new User FirstName";
у меня не проходят тесты этого класса из-за нарушения длины поля first name в БД 
<img width="630" alt="Снимок экрана 2024-01-20 013908" src="https://github.com/pymanceva/pet-hotel/assets/119865569/bcb95109-2eee-475c-83e9-b8767df441b8">

2024-01-19 22:44 UTC, pymanceva commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceIntegrationTest.java
> +    final String userMiddleName = "new User MiddleName";
у middle name тоже лимит в 15 символов, а тут 19

2024-01-20 02:57 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/IntegrationTest.java
> +public class IntegrationTest {
Проверяю работу всех слоёв вместе. От контроллера до базы.
Вспомнил, что был такой интеграционный тест на учёбе, решил его применить.

2024-01-20 02:59 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceIntegrationTest.java
> +    final String userFirstName = "new User FirstName";
Это странно. У меня были такие же проблемы, я от них избавлялся. Запускал все тесты - косяков не наблюдалось. Исправлю, конечно же.

2024-01-20 02:59 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceIntegrationTest.java
> +    final String userMiddleName = "new User MiddleName";
Проверю всё ещё раз.

2024-01-23 17:32 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/IntegrationTest.java
> +    final String userLastName = "Мартынов";
я старался =)

2024-01-24 00:33 UTC, pymanceva approved these changes
все кул)

2024-01-30 04:46 UTC, alisilakg approved these changes
Всё посмотрела. Ты молодец. Аппрув.
В комментариях незначительные замечания и мои недопонимания.

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        NewUserDto newUserDto = new NewUserDto(userLastName, userFirstName, userMiddleName, email, userPassword,
Очень много дублированного кода из-за того, что юзеры не вынесены в поля, а создаются внутри каждого теста

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +                () -> assertEquals(expectedUserDto, returnedUserDto),
Здесь проверяются на равенства два объекта со всеми полями равными null)))) Я не понимаю, какой в этом смысл, потому что при любом раскладе объекты будут идентичные. 

И зачем excpectedUser присваивать роль админа, если уже в excpectedUserDto этой роли нет?)))))

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +                () -> assertEquals(expectedUserDto, returnedUserDto),
тоже самое к последующим тестам относится...

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        Roles newUserRole = null;
Зачем здесь эта строка, если переменная newUserRole нигде в тесте не используется?))))

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto2 = UserDto.builder()
В этом тесте переменная userDto2 не используется, но написана))))

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto1 = UserDto.builder()
не используется в этом тесте

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto3 = UserDto.builder()
тоже самое здесь и в последующих тестах

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +    void getAllUsers_whenAdminGetAllUsers_returnAllUsersThanBoss() {
Вот этот тест меня запутал. Почему возвращаются все пользователи кроме босса: потому что админ может получить информацию о всех пользователях кроме босса(ни в сценарии, ни в сваггере такого требования не нашла, хотя оно логичное) или потому что босс единственный пользователь с полем isActive = false(хотя я не могу представить ситуации, когда в по босс может быть не активным)?

В общем, на мой взгляд, лучше где-то отметить в документации, что админ получит всех пользователей, кроме босса

2024-01-30 04:46 UTC, alisilakg commented on src/test/java/ru/dogudacha/PetHotel/user/IntegrationTest.java
> +public class IntegrationTest {
Отличная идея - написать такие тесты!

2024-02-01 03:05 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +                () -> assertEquals(expectedUserDto, returnedUserDto),
Наверное дело в покрытии тестами метода =)

2024-02-01 03:06 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        Roles newUserRole = null;
Артефакты =)

2024-02-01 03:06 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto2 = UserDto.builder()
Скорее всего для единообразия с другими тестами =)

2024-02-01 03:06 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto1 = UserDto.builder()
Единообразие =)

2024-02-01 03:06 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +        UserDto userDto3 = UserDto.builder()
То же самое =)

2024-02-01 03:07 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/user/service/UserServiceImplTest.java
> +    void getAllUsers_whenAdminGetAllUsers_returnAllUsersThanBoss() {
Потому, что пользователи могут получать список пользователей ролью не выше своей. В сваггер надо вносить изменения =)

2024-02-01 03:08 UTC, merged