Add check room availabity
pymanceva/pet-hotel pull request #43
Opened 2024-05-30 12:47 UTC by pymanceva

Карточки: https://nkiblyk.kaiten.ru/space/167883/card/27548967?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImNvbXBhcmlzb24iOiJlcSIsImtleSI6InJlc3BvbnNpYmxlIiwidmFsdWUiOjQ5NDU3MH1dfV19

https://nkiblyk.kaiten.ru/space/167883/card/27548993?filter=eyJrZXkiOiJhbmQiLCJ2YWx1ZSI6W3sia2V5IjoiYW5kIiwidmFsdWUiOlt7ImNvbXBhcmlzb24iOiJlcSIsImtleSI6InJlc3BvbnNpYmxlIiwidmFsdWUiOjQ5NDU3MH1dfV19

US: https://docs.google.com/document/d/1yG7TwO6sCLbJMLEOxF_YmKiB2seioYF4fFHz6Uc-weU/edit
US: https://nkiblyk.kaiten.ru/documents/d/7a1c8a2d-b776-45bc-adcf-0a7091b5a9bc

2024-06-10 09:30 UTC, RodionovRL requested changes
Отличная работа. Мы плавно движемся к нашей цели =)
Нужно внести немного правок. И учесть некоторые нюансы в связи с перспективой возникновения конфликтов при мерже.
Я не кидал запросы, принял за данность, что в этом плане всё работает.

2024-06-10 09:30 UTC, RodionovRL commented on pet-hotel-versions/CHANGELOG.md
> +**0.0.12: Добавлена проверка доступности номеров, поиск блокирующих и пересекающихся бронирований
Номер версии не угадала =)

2024-06-10 09:30 UTC, RodionovRL commented on pet-hotel-versions/docker-compose.yaml
> +    build: modgy-back-0.0.9
почему именно эта папка?

2024-06-10 09:30 UTC, RodionovRL commented on pom.xml
> +	<version>0.0.12-SNAPSHOT</version>
0.0.13

2024-06-10 09:30 UTC, RodionovRL commented on specification/pet-hotel-rooms-spec.yaml
>        summary: Получение списка всех номеров
Что-то не нашёл в юзерстори запрос всех номеров.

2024-06-10 09:30 UTC, RodionovRL commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение списка всех номеров. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
Финансист тоже может просматривать список всех номеров? Не нашёл в Юзерстори

2024-06-10 09:30 UTC, RodionovRL commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение номера по его ID. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
Финансист может просматривать номер? Не нашёл в Юзерстори

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingService.java
Javadoc - красотища =)

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
> +            checkRoom(room);
Здесь вызывается метод, в котором проверяется isAvalible с текстом ошибки:
"Can't add booking for hidden room"
при этом мы не добавляем, а апдейтим наше бронирование.

Возможным решением видится передача в метод не только объекта Room, но и текст, который будет выдан при ошибке.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
> +            checkRoom(room);
ЗанудаMode on 
было бы круто, если бы это вылезло на тестах.
ЗанудаMode off

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/owner/dto/mapper/OwnerMapper.java
Вангую здесь конфликт при меже =)

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/controller/PetController.java
> +    @GetMapping("/search")
Не понял как в этом ПР оказался поиск питомцев, ну да ладно =)

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/dto/NewPetDto.java
> +//todo    @NotNull(message = "Field: owner. Error: must not be blank.")
Красотища =)

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/model/Pet.java
> +//        @ManyToOne()
TODO?

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/model/Pet.java
> +    @CreationTimestamp
Элегантно.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/model/TypeOfPet.java
> +    DOG,
сместили пёселя по алфовиту?

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/repository/PetRepository.java
>  //    Pet findByOwnerAndName(long ownerId, String namePet);
TODO

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/service/PetServiceImpl.java
>      //метод проверки наличия хозяина питомца, будет дописан после добавления сущности оунеров
todo

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        utilityService.checkBossAdminFinancialAccess(requesterId);
Вопрос про финансиста аналогичен вопросу в сваггере

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        utilityService.checkBossAdminFinancialAccess(requesterId);
вопрос про финансиста

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Валидировать параметры не будем?

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/category/service/CategoryServiceImpl.java
> -    public Category findCategoryById(Long id) {
Любопытно, что метод был публичный

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/dto/mapper/RoomMapper.java
> +    @Mapping(source = "roomDto.categoryDto", target = "category")
Тоже красиво.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/room/service/RoomService.java
м-м-м-м, JavaDoc  
![image](https://github.com/pymanceva/pet-hotel/assets/114774699/d7861105-d339-41ca-85c0-3f2e512c4be6)

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/user/controller/UserController.java
Здесь будет конфликт, прошу мою версию считать верной.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/user/service/UserServiceImpl.java
Здесь тоже может быть конфликт. Я уже проверял работу этого сервиса, когда писал оунеров.
Странно, это не в девелопе (только что понял это).

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/utility/EntityService.java
Обратно к вопросу о том, что утилитарки нету в develop до того, как случился ПР.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/utility/UtilityService.java
Обратно к утилитарному классу.

2024-06-10 09:30 UTC, RodionovRL commented on src/test/java/ru/modgy/booking/BookingControllerTest.java
> +                        .param("checkOutDate", "2024-01-02"))
Почему дата в формате ГГГГ.ММ.ДД?

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
>              newBooking.setStatus(StatusBooking.STATUS_CONFIRMED);
А чем-то обусловлено использование жёстких & и | вместо && и ||? 
Если нет, но надо заменить везде.

2024-06-10 09:30 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
238 строка:
```
 if (type.equals(TypesBooking.TYPE_CLOSING)) {
            if (reason == null) {
```

можно написать симпатичнее с использованием &&

2024-06-10 09:30 UTC, RodionovRL commented on src/test/java/ru/modgy/booking/BookingControllerTest.java
>  public class BookingControllerTest {
здесь public не нужен, как и в остальных тестах

2024-06-10 09:59 UTC, pymanceva commented on pet-hotel-versions/CHANGELOG.md
> +**0.0.12: Добавлена проверка доступности номеров, поиск блокирующих и пересекающихся бронирований
на момент ПР ты не мержил, естественно, я ставила номер по порядку. Мы ранее уже обсуждали это, мне так удобнее, потом перед мержем правлю версию

2024-06-10 10:00 UTC, pymanceva commented on pet-hotel-versions/docker-compose.yaml
> +    build: modgy-back-0.0.9
я не трогала докер, это то что прилетело с чужих правок. Честно говоря, уже вообще не понимаю, как гитхаб отражает изменения. Это не мои исправления

2024-06-10 10:00 UTC, pymanceva commented on pom.xml
> +	<version>0.0.12-SNAPSHOT</version>
про версию выше написала

2024-06-10 10:01 UTC, pymanceva commented on specification/pet-hotel-rooms-spec.yaml
>        summary: Получение списка всех номеров
это старый код, написанный ранее, прошедший ревью ранее, еще до прихода Наташи и написания юзерстори.

2024-06-10 10:02 UTC, pymanceva commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение списка всех номеров. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
это старый код, написанный ранее, прошедший ревью ранее, еще до прихода Наташи и написания юзерстори. На тот момент мы обсуждали доступ к инфо о номерах у финансиста в том числе. Чтобы он имел возможность смотреть, сколько у гостиницы их всего, каких категорий, какая стандарт цена и т.п. Для фин прогнозов и тп

2024-06-10 10:02 UTC, pymanceva commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение номера по его ID. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
отвечала выше

2024-06-10 10:03 UTC, RodionovRL commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение списка всех номеров. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
Давай попросим Наташу подправить юзерстори, наверное так будет правильно?

2024-06-10 10:06 UTC, pymanceva commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
> +            checkRoom(room);
При обновлении бронирования также обновленная инфа добавляется в базу. Да, она вымещает старую, но мы даже метод используем тот же, что и при создании нового объекта - save. Кроме того, в рамках возможного выплывания этой ошибки - мы меняем номер в брони. То есть для нового номера - это попытка добавить бронирование. Ранее у номера этой брони не было. Так что формально тоже текст подходит

2024-06-10 10:07 UTC, pymanceva commented on src/main/java/ru/modgy/owner/dto/mapper/OwnerMapper.java
да, но конфликты есть всегда, выбрать версию девелопа не проблема. А без этого не билдился проект в принципе

2024-06-10 10:07 UTC, pymanceva commented on src/main/java/ru/modgy/pet/controller/PetController.java
> +    @GetMapping("/search")
я вообще хз, реально. Иногда неведомым образов влетают чужие блоки, и в большом количестве. В питомцах тогда все юзеры засветились, помню. Тут питомцы

2024-06-10 10:08 UTC, pymanceva commented on src/main/java/ru/modgy/pet/dto/NewPetDto.java
> +//todo    @NotNull(message = "Field: owner. Error: must not be blank.")
это даже не мое))) это Кристинины питомцы)

2024-06-10 10:08 UTC, pymanceva commented on src/main/java/ru/modgy/pet/model/Pet.java
> +//        @ManyToOne()
Снова не мое, питомцев пишет Кристина

2024-06-10 10:09 UTC, pymanceva commented on src/main/java/ru/modgy/pet/model/TypeOfPet.java
> +    DOG,
аналогично

2024-06-10 10:09 UTC, pymanceva commented on src/main/java/ru/modgy/room/RoomController.java
> +        utilityService.checkBossAdminFinancialAccess(requesterId);
ранее ответила, да

2024-06-10 10:12 UTC, pymanceva commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
валидировать что именно? Ранее в контроллерах также ничего не валидировали, чисто required уточняли, если вдруг он false.

2024-06-10 10:14 UTC, pymanceva commented on src/main/java/ru/modgy/user/service/UserServiceImpl.java
ты смержил оунеров после ПР, так что тут многое из твоей ветки отсутствует. Повторюсь - конфликты есть в 99% случаев. Если будут сомнения при мерже - я приду с ними в чат. В остальном не понимаю сути комментариев)))

2024-06-10 10:16 UTC, pymanceva commented on src/main/java/ru/modgy/utility/EntityService.java
Есть, я же сначала ту задачу до конца добила и смержила, потом еще все тут правила под утилитарку, потому что код был начат без него. На момент ПР утилитарка была в девелопе. Но каким боком это идет в текущий ПР - я не могу прокомментировать, не понимаю.

2024-06-10 10:18 UTC, RodionovRL commented on src/main/java/ru/modgy/utility/EntityService.java
Ага, нонял :)

2024-06-10 10:19 UTC, RodionovRL commented on src/main/java/ru/modgy/user/service/UserServiceImpl.java
Теперь понял :)

2024-06-10 10:21 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Ну если разобраться, то всегда именно в контроллере всё и валидируется. 
(Аннотации над полями во входящих dto)
Здесь можно даты валидировать, чтобы они были в правильном порядке и диапазоне, например.

2024-06-10 10:22 UTC, RodionovRL commented on src/main/java/ru/modgy/pet/controller/PetController.java
> +    @GetMapping("/search")
Чудные дела :) 
Ну да шут с ним :)

2024-06-10 10:24 UTC, pymanceva commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
Можно вообще все переписать))) Это старый код, он даже не редактировался и по ошибке в текущий ПР не влетел. Если ты полагаешь, что эти правки необходимы - давай задачу в бэклог, в какой-то момент доберемся. В рамках текущей ветки это будет противоречием твоим же правилам, про то, чтобы на все отдельные задачи были

2024-06-10 10:30 UTC, pymanceva commented on pet-hotel-versions/docker-compose.yaml
> +    build: modgy-back-0.0.9
единственное - подвигала папки. Мы как-то обсуждали, что у нас докерфайл в каждую папку идет, и changelog, и т.д. Я их вынесла выше, в в папках версий оставила только jar. Но внутрянке в докерфайле и докеркомпоузе не трогала

2024-06-10 10:31 UTC, pymanceva commented on specification/pet-hotel-rooms-spec.yaml
> +      description: Получение списка всех номеров. Доступно только пользователями с ролью ROLE_BOSS, ROLE_ADMIN, ROLE_FINANCIAL.
я не против, но если будем править старый код - все равно в отдельную задачу, не в рамках нынешней. Так что оставляю resolved, и далее видно будет

2024-06-10 10:41 UTC, pymanceva commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
диапазон дат я затрудняюсь установить. Какие критерии взять? Просто из головы решить, что допустим 1900 год - вряд ли? Но где тогда грань? И про будущее также.
В сервисе я проверяю, чтобы дата заезда не была позже даты выезда, считаю так и нужно оставить, контроллер проверил наличие дат, ну и в целом формат, что это дата, а не что-то еще. А то, что они должны определенным образом между собой соотноситься - это же логика, это в сервис

2024-06-10 10:44 UTC, RodionovRL commented on pet-hotel-versions/docker-compose.yaml
> +    build: modgy-back-0.0.9
Оставляй как есть.

2024-06-10 10:55 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Ну чтобы зря в сервис не ходить проверить, что даты не из прошлого, например. Мы ведь здесь проверяем доступность номера. Зачем нам эти данные из прошлого?

2024-06-10 11:01 UTC, pymanceva commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Тут я уже идейно не согласна. Я могу захотеть добавить старую бронь, ы прошлом, она добавляться будет так же как и будущая, с проверкой доступности. Это может потребоваться для исправления ошибки (случайно удалили), или для корректной статистики (например, внесли старые брони по клиенту, хотим видеть исчерпывающую историю бронирований). Короче, даты в прошлом - ок

2024-06-10 11:02 UTC, pymanceva commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Кажется, мы это в таком же ключе обсуждали при планировании ограничений в БД. И тоже тогда решили, что и задним числом всё вносить можно

2024-06-10 11:51 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
> +            checkRoom(room);
Ну название метода значения не имеет, конечно. Здесь скорее про то, что, если мы обновляем что-то, то странно в ответ получить, что не удалось создать(мы ведь и не создавали ничего, мы уже созданное редактируем)

2024-06-10 11:52 UTC, RodionovRL commented on src/main/java/ru/modgy/room/RoomController.java
> +        log.info("RoomController: GET/getAvailableRoomsByCategoryInDates, " +
Ну ок

2024-06-10 12:00 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/service/BookingServiceImpl.java
Да, значит надо карточку создать.

2024-06-12 13:10 UTC, RodionovRL approved these changes

2024-06-12 14:55 UTC, merged