feat: соединила клиентов и питомцев
pymanceva/pet-hotel pull request #52
Opened 2024-08-21 10:18 UTC by alisilakg

2024-08-22 20:58 UTC, pymanceva requested changes
Отличная работа, по нюансам логики написала по комментариям. Если питомцев в NewOwnerDto оставляем все таки - тогда надо в бэклог добавить задачу на обработку питомцев в сервисе оунеров, думаю пока это будет не срочная задача

2024-08-22 20:58 UTC, pymanceva commented on specification/pet-hotel-owner-spec.yaml
> +        petsDto:
не уверена, что нужен список айди питомцев при создании клиента. Мне казалось, мы просто создаем клиента отдельно, он может в теории и без животных быть пока. А вот питомец без владельца нам не подходит. Ну я из карточек и фигмы так поняла. Там указан раздел добавления питомца (пустой), но он для добавления нвых питомцев в базу, как я понимаю, а не для соединения существующих питомцев с этим клиентом. К тому же, сейчас с этими id ничего не делается в сервисе, то есть мы их принимаем, но назад возвращается клиент с питомцами null.

2024-08-22 20:58 UTC, pymanceva commented on src/main/resources/schema.sql
> +    owner_id_pets                  BIGINT                                          ,
у меня не грузится draw.io, чтобы посмотреть ER-диаграмму от Наташи, но мн кажется это поле должно быть NOT NULL. Соответсвенно, надо будет поправить запись INSERT для питомца и добавить INSERT для оунера

2024-08-22 20:58 UTC, pymanceva commented on src/main/java/ru/modgy/pet/mapper/PetMapper.java
> +    @Mapping(target = "ownerShortDto", ignore = true)
либо нужно доработать автоматизацию маппинга, либо добавить ручное добавление OwnerShortFto в питомцах в бронированиях, фронтам нужна эта инфа, а сейчас возвращается null

2024-08-23 05:26 UTC, alisilakg commented on specification/pet-hotel-owner-spec.yaml
> +        petsDto:
да, ты права здесь список питомцев не нужен

2024-08-23 06:36 UTC, alisilakg commented on src/main/java/ru/modgy/pet/mapper/PetMapper.java
> +    @Mapping(target = "ownerShortDto", ignore = true)
автоматический маппинг у меня не получилось настроить, возникает циклическая зависимость

сделала ручное добавление

2024-08-23 06:38 UTC, alisilakg commented on src/main/resources/schema.sql
> +    owner_id_pets                  BIGINT                                          ,
да, верно

2024-08-23 11:40 UTC, pymanceva approved these changes

2024-09-05 18:26 UTC, merged