feature/#36490897 Связать питомцев и бронирования.
pymanceva/pet-hotel pull request #54
Opened 2024-09-02 09:18 UTC by RodionovRL

[Ссылка на карточку в Кайтен](https://nkiblyk.kaiten.ru/space/167883/card/36490897)

2024-09-04 12:30 UTC, pymanceva requested changes
Отличная работа! Пару комментариев по коду оставила, и также нужно поправить сваггер по питомцам - теперь у PetDto имеется поле с бронированиями, в свагер нужно добавить объект BookingForPetDto и его включить в PetDto. 

Да, нюансы по BookingForPetDto - это на обсуждение, а не прям строго)

2024-09-04 12:30 UTC, pymanceva commented on src/main/java/ru/modgy/booking/dto/BookingForPetDto.java
> +    private TypesBooking type;
если верно понимаю, то у бронирования, связанного с питомцем, всегда один тип - бронирование, т.е. в этой дто можно отдельно тип не указывать

2024-09-04 12:30 UTC, pymanceva commented on src/main/java/ru/modgy/booking/dto/BookingForPetDto.java
> +    private ReasonOfStopBooking reasonOfStop;
это поле также свойственно только для бронирования типа закрытие, т.е. у связанной с питомцем брони его быть не может, можно убрать лишнее

2024-09-04 12:30 UTC, pymanceva commented on src/main/java/ru/modgy/utility/EntityService.java
> +//        return petRepository.findById(petId).orElseThrow(() ->
коммент забытый

2024-09-04 12:30 UTC, pymanceva commented on src/main/resources/schema.sql
> +INSERT INTO public.bookings (id_bookings, type_bookings, check_in_date_bookings, check_out_date_bookings,
расскажи, пожалуйста, почему public.bookings вместо стандартного инсерта через название таблицы? Что дает public?

2024-09-04 13:24 UTC, RodionovRL commented on src/main/resources/schema.sql
> +INSERT INTO public.bookings (id_bookings, type_bookings, check_in_date_bookings, check_out_date_bookings,
public - это название схемы.
Я руками добавил через идею прям в табличку и сгенерил оттуда этот код. А Идея решила, что ей нужно дополнительно указать схему.

2024-10-23 02:58 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/dto/BookingForPetDto.java
> +    private TypesBooking type;
Убрал

2024-10-23 02:58 UTC, RodionovRL commented on src/main/java/ru/modgy/booking/dto/BookingForPetDto.java
> +    private ReasonOfStopBooking reasonOfStop;
Убрал

2024-11-13 12:01 UTC, pymanceva approved these changes

2024-11-13 12:02 UTC, merged