Add rooms
pymanceva/pet-hotel pull request #6
Opened 2023-10-24 23:16 UTC by pymanceva

2023-10-25 08:14 UTC, RodionovRL requested changes

2023-10-25 08:14 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/RoomController.java
> +        log.info("receive DELETE request fo delete room with id= {}", roomId);
for

2023-10-25 08:14 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/dto/RoomDto.java
> +    private Boolean isAvailable;
А здесь может быть Null?

2023-10-25 08:14 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/service/RoomServiceImpl.java
> +        checkAdminAccess(userId);
Здесь я за однообразие.
Предлагаю сначала получить юзера, а потом чекнуть его права.
В разных приватных методах.
Тогда не придётся повторять код получения пользователя (и выбрасывания исключений) в каждом чек-методе прав.

2023-10-25 08:14 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/model/Room.java
> +    RoomTypes type;
private

2023-10-25 08:14 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/service/RoomServiceImpl.java
> +                new NotFoundException(String.format("user with id=%d not found", userId)));
О чём написал выше.
DRY

2023-10-25 08:14 UTC, RodionovRL commented on src/main/resources/schema.sql
> +    size      REAL,
Price и size могут быть null?

2023-10-25 08:35 UTC, pymanceva commented on src/main/resources/schema.sql
> +    size      REAL,
Да, могут. Номер может не иметь типовой цены вообще, либо для конкретной гостиницы это не важно (например, строго индивидуальная ценовая сетка). Про размер - один из форматов пробивание как дома, там вообще нет номера в полном смысле слова, но вся логика от номера сохраняется. Но у такой штуки нет размера. Аналогично с местами для всяких птичек, хомячков - нужно учитывать их размещение, но по факту площадь номера - это размер их клетки, в которой они приехали

2023-10-25 08:36 UTC, pymanceva commented on src/main/java/ru/dogudacha/PetHotel/room/dto/RoomDto.java
> +    private Boolean isAvailable;
Available можно не указывать в ДТО, по умолчанию ставится true

2023-10-26 03:27 UTC, RodionovRL commented on src/main/java/ru/dogudacha/PetHotel/room/service/RoomServiceImpl.java
> +        checkAdminAccess(userId);
И если нету проверки прав, не забудешь проверить наличие пользователя. Он должен быть независимо от необходимости проверки прав.

2023-10-26 03:32 UTC, RodionovRL requested changes

2023-10-26 03:32 UTC, RodionovRL commented on src/test/java/ru/dogudacha/PetHotel/room/service/RoomServiceImplTest.java
> +        verify(roomRepository, times(1)).findById(anyLong());
Здесь можно вставить проверку вызова всех моков, что указаны выше и тогда поймать ошибку, что забыла проверить наличие юзера.

2023-10-28 11:46 UTC, RodionovRL approved these changes

2023-11-02 06:36 UTC, merged